// palette.js — emotion colors and emotional scale order
export const emotionScale = [
  'Joy', 'Appreciation', 'Empowered', 'Freedom', 'Love',
  'Passion',
  'Enthusiasm', 'Eagerness', 'Happiness',
  'Positive Expectation', 'Belief', 'Optimism',
  'Hopefulness',
  'Contentment',
  'Boredom',
  'Pessimism',
  'Frustration', 'Irritation', 'Impatience',
  'Overwhelm',
  'Doubt',
  'Worry',
  'Blame',
  'Discouragement',
  'Anger', 'Revenge',
  'Hatred', 'Rage',
  'Jealousy',
  'Insecurity', 'Guilt', 'Unworthiness',
  'Fear', 'Grief', 'Despair', 'Powerlessness'
];

export const emotionColors = {
  'Joy': '#FFD700',
  'Appreciation': '#FFA500',
  'Empowered': '#FF8C00',
  'Freedom': '#FF6347',
  'Love': '#FF1493',
  'Passion': '#DC143C',
  'Enthusiasm': '#B22222',
  'Eagerness': '#8B0000',
  'Happiness': '#FF4500',
  'Positive Expectation': '#FF6347',
  'Positive': '#FF6347',
  'Belief': '#FF7F50',
  'Optimism': '#FFA07A',
  'Hopefulness': '#F0E68C',
  'Contentment': '#ADFF2F',
  'Boredom': '#90EE90',
  'Pessimism': '#32CD32',
  'Frustration': '#228B22',
  'Irritation': '#006400',
  'Impatience': '#008000',
  'Overwhelm': '#2E8B57',
  'Doubt': '#20B2AA',
  'Worry': '#48D1CC',
  'Blame': '#40E0D0',
  'Discouragement': '#00CED1',
  'Anger': '#5F9EA0',
  'Revenge': '#4682B4',
  'Hatred': '#4169E1',
  'Rage': '#0000FF',
  'Jealousy': '#00008B',
  'Insecurity': '#191970',
  'Guilt': '#483D8B',
  'Unworthiness': '#6A5ACD',
  'Fear': '#7B68EE',
  'Grief': '#9370DB',
  'Despair': '#8A2BE2',
  'Powerlessness': '#4B0082'
};

// base stops for multi-emotion gradients
export const baseStops = ['#ff3b8d', '#ff7a59', '#ffd54a'];
